### ISSUE TITLE
Escaping ' in char lists not working. 

### ISSUE THREAD

**Issue by bgianfo** [elixir-lang/vim-elixir#100]
For a repro, see the following example from: lib\elixir\lib\uri.ex 

      def char_reserved?(c) do
        c in ':/?#[]@!$&\'()*+,;='
      end

Seems that \' isn't being escaped properly. 

![image](https://cloud.githubusercontent.com/assets/1212/5562808/913960a6-8df1-11e4-98cc-81cabfd87777.png)

**Comment by whatyouhide** [comment]
Hi @bgianfo, why did you close #101? Seemed like a fine solution to me :smiley:.

**Comment by bgianfo** [comment]
Didn't work, it failed the test suite for a different feature...

Closed it as it I couldn't run the test suite on my machine at the time (
was stuck on a windows box ) and didn't have any more time to put into the
investigation.
