### ISSUE TITLE
the syntastic plugin is unhappy with a default `mix.exs`

### ISSUE THREAD

**Issue by killerswan** [elixir-lang/vim-elixir#117]
These errors (on opening the file, or saving) seem unfortunate:
```
Error detected while processing function <SNR>55_BufWritePostHook..<SNR>55_UpdateErrors..<SNR>55_Cache
Errors..240..239:
line    5:
E691: Can only compare List with List
E15: Invalid expression: status < 0
Error detected while processing function <SNR>55_BufWritePostHook..<SNR>55_UpdateErrors..<SNR>55_Cache
Errors..240..262:
line    3:
E712: Argument of filter() must be a List or Dictionary
```

That's on OS X with syntastic 3.6.0-130 (master, [here](https://github.com/scrooloose/syntastic/tree/76ec53f186d1e6)) and Mix 1.0.5, after typing:
```
mix new portal --sup
gvim portal/mix.exs
```

After, also, enabling the syntax checker with these in my `.vimrc`:
```
let g:syntastic_elixir_checkers = ['elixir']
let g:syntastic_enable_elixir_checker = ['elixir'] 
```

**Comment by kassio** [comment]
Those functions are from `syntastic`. You should open this issue there. :smile:

**Comment by killerswan** [comment]
What's the version of Syntastic where this Elixir checker works for you, @kassio?  I'll install that if you know it. :)

**Comment by kassio** [comment]
Actually I'm not using syntastic. :blush: But the function mentioned on the error `55_BufWritePostHook`, it's from syntastic.

**Comment by killerswan** [comment]
I've poked around under the hood enough now.  If syntastic had this patch, I'd not have complained:
https://github.com/scrooloose/syntastic/compare/master...killerswan:checker_enable_typecheck

And would have realized I needed this, instead:
```
let g:syntastic_elixir_checkers = ['elixir']
let g:syntastic_enable_elixir_checker = 1
```

:D

**Comment by kassio** [comment]
@killerswan nice! Now you just need to open a pull request there. :smile:
