### ISSUE TITLE
Integration with Vim Projectionist

### ISSUE THREAD

**Issue by patrickdavey** [elixir-lang/vim-elixir#119]
Hi there,

I love your plugin, I was wondering if you have any thoughts on incorporating https://github.com/tpope/vim-projectionist into vim-elixir  (see https://github.com/tpope/vim-rails which leans on it heavily I believe)

I have no clue how to do this (though I'm tempted to give it a try!).. as a vim-rails user it's really nice to be in a file and to type `:A` and get taken to the alternate file (e.g. from a model to a model spec).  to be able to run a test by going `.Rake`.  I'm utterly new to elixir, and I've never tried writing a vim plugin, but just wondering if this sort of feature is something you'd be interested in / see on your road map, or if you are sticking to syntax ?  There's also https://github.com/mattreduce/vim-mix which might be a better fit?

**Comment by carlosgaldino** [comment]
That's cool but I think it's better not to add more dependencies here. If someone wants to have the same behavior that `vim-rails` provides they can either create their own config file for `vim-projectionist` or use this other plugin you mentioned.

Thank you.
