### ISSUE TITLE
Color for `do end` regression

### ISSUE THREAD

**Issue by larrylv** [elixir-lang/vim-elixir#128]
```
$ git last
commit 6e58b17f6bbf4be396f661120162417a8293757b
Author: Kassio Borges <kassioborgesm@gmail.com>
Date:   Fri Jan 1 22:34:17 2016 -0300
```

When I use this commit of `vim-elixir`, `do end` color looks fine:
![screen shot 2016-01-08 at 1 11 15 pm](https://cloud.githubusercontent.com/assets/531650/12190963/aa58c0c2-b609-11e5-9f6f-bb3f817c820f.png)

But after this recent commit 788a50bb761a5e4d59da30e6dc449cd4e41947a0, `do` and `end` have the same color with `def` now:
```
$ git log 788a50b -1
commit 788a50bb761a5e4d59da30e6dc449cd4e41947a0
Author: Kassio Borges <kassioborgesm@gmail.com>
Date:   Sat Jan 2 17:41:02 2016 -0300

    Create a `elixirBlockDefinition` syntax

    This use `Define` colors on `do`/`end` and `fn`/`end` blocks.
$ git merge 788a50b
Updating 6e58b17..788a50b
Fast-forward
 syntax/elixir.vim | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)
```
![screen shot 2016-01-08 at 1 13 18 pm](https://cloud.githubusercontent.com/assets/531650/12190961/a442b5d0-b609-11e5-89ce-55698a3e452b.png)

Also, auto completion of `end` for `do` after pressing return doesn't work either. This is [vim-endwise](https://github.com/tpope/vim-endwise/blob/526fe36bd23120077f65856fe986c64a3e49a03a/plugin/endwise.vim#L19)'s job, but it did work before, and after commit 788a50b, it didn't work.

**Comment by kassio** [comment]
I'll revert the new colors and open a pull request on vim-endwise updating the `syngroup` there.

**Comment by larrylv** [comment]
@kassio Thanks for you quick response. The color is back now, I will subscribe your pr for `vim-endwise` and close this issue once it got merged.

**Comment by larrylv** [comment]
All worked as before, thanks @kassio
