### ISSUE TITLE
indentation broken with `function :atom`

### ISSUE THREAD

**Issue by asymmetric** [elixir-lang/vim-elixir#129]
Typing a statement like `plug :match` somehow breaks indentation. What's breaking things is not `plug`, as that receives no special treatment (sidenote: should it?), it's the atom that follows.

![screenshot from 2016-01-08 16-45-29](https://cloud.githubusercontent.com/assets/101816/12201928/45698d54-b627-11e5-8ad2-dfc98874ddc3.png)

![screenshot from 2016-01-08 16-39-24](https://cloud.githubusercontent.com/assets/101816/12201761/64b2bf10-b626-11e5-8614-960c209a74de.png)

Running dee2758.

**Comment by kassio** [comment]
In this case the problem is the particular atom `:match`. I'll fix it.
