### ISSUE TITLE
How to change the indentation

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [elixir-lang/vim-elixir#134]
I don't really like 9 spaces when I press tab as the default indentation. I would like to be able to change it to 4 spaces per indentation or when I press tab. Is there anyway to change that, since I don't see any help txt file. Thank you!

**Comment by kassio** [comment]
Sorry, but I don't think this is about this plugin in particular. I guess you should change your vim config with something like `set tabstop=2 shiftwidth=2 softtabstop=2`.
