### ISSUE TITLE
Sigil highlighting error on escape ")" character

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#138]
In this case I have a sigilized string with an escaped closing paren

```ex
iex(2)> ~s(ruby -e '[].push('123'\))
"ruby -e '[].push('123')"
```

However the syntax rules don't seem to check for escaped sigils

<img width="275" alt="1__deployer_exs______repos_backupify_scripts__-_vim__vim_" src="https://cloud.githubusercontent.com/assets/6093002/12829028/efe413e2-cb55-11e5-877b-5b9f04d70299.png">

**Comment by kassio** [comment]
Actually, the vim-elixir use different syntax groups for the sigil delimiter, its content and content escapes. However, it's possible that your current colorscheme are using similar colors for `Special` (used for escapes) and `Delimiter` (used for the sigil delimiters).

My current theme (Ocean-Next) these two syntax grous have different colors:

![screen shot 2016-02-04 at 11 29 44 pm](https://cloud.githubusercontent.com/assets/120483/12835441/4ac2509e-cb97-11e5-83a0-cc10b12c4dfa.png)

**Example**
![menubar_and_nvim](https://cloud.githubusercontent.com/assets/120483/12835399/eabef724-cb96-11e5-9af1-7c25e763e08d.png)
