### ISSUE TITLE
Broken color syntax for case

### ISSUE THREAD

**Issue by ArturT** [elixir-lang/vim-elixir#144]
I noticed problem with missing color for `end` words and closing `}` in `{int, _} when int > 0...`

Example code:
```elixir
defmodule Rumbl.Permalink do
  def cast(binary) when is_binary(binary) do
    case Integer.parse(binary) do
      {int, _} when int > 0 -> {:ok, int}
      _ -> :error
    end
  end
end
```

**Comment by kassio** [comment]
I wasn't able to replicate this, all my `end`s are colorful:
![menubar_and_vim](https://cloud.githubusercontent.com/assets/120483/14573472/a95ea2f8-032b-11e6-916d-85d06156662f.png)

**Comment by ArturT** [comment]
It turns out it was fault of another plugin https://github.com/kien/rainbow_parentheses.vim
I also tried different plugin https://github.com/luochen1990/rainbow but the same problem occurred so I'm not sure if the problem is mostly on those plugin sides or anything is wrong here.

![elixir-syntax](https://cloud.githubusercontent.com/assets/662545/14587121/333047b6-04ad-11e6-9826-8d279549b20a.png)

**Comment by kassio** [comment]
I tried again loading only the vim-elixir (with vim-plug), vim version 7.4-1-1748:

![vim](https://cloud.githubusercontent.com/assets/120483/14587792/c1107e52-048f-11e6-9b37-f9a73927764e.png)


Can you do the same test, load only the vim-elixir, with your environment?

**Comment by ArturT** [comment]
It works fine with only vim-elixir 
![only elixir-vim](https://cloud.githubusercontent.com/assets/662545/14588169/0654d55c-04c3-11e6-950d-78f69cb21651.png)

When I added one of rainbow plugins then colors were messed up as here
![elixir-syntax](https://cloud.githubusercontent.com/assets/662545/14587121/333047b6-04ad-11e6-9826-8d279549b20a.png)

I guess we can close this issue. It should be fixed in rainbow plugins.
