### ISSUE TITLE
Module view optimization - "end" excess syntax

### ISSUE THREAD

**Issue by henry-hz** [elixir-lang/vim-elixir#147]
Please, let me ask you an option to change the "end" syntax in elixir to another color that is similar to the background, or almost make it completely transparent, once the "end" is not necessary in the functional scenario, and it will be really more clear and fast to read the elixir module.

**Comment by kassio** [comment]
Hello @henry-hz. Today we don't have this option, and I don't agree very much with this bringing value to Elixir syntax reading. The `end` words may not be relevant in the function scenario, but they are relevant to the syntax, this is why we match it with the beginning of the block.
