### ISSUE TITLE
adding `end` to new function/module blocks

### ISSUE THREAD

**Issue by desmondmonster** [elixir-lang/vim-elixir#148]
the vim-ruby plugin will add an `end` on a newline when I define a class, method, block, etc.  Does elixir-vim support this?  If so, it's not working on my machine :/

**Comment by arturts** [comment]
from the README, the features included are Syntax highlighting, Filetype detection and Automatic indentation.
For that functionality, take a look at [vim-snippets](https://github.com/honza/vim-snippets). There's support for a lot of programming languages, including elixir.

**Comment by desmondmonster** [comment]
honestly I couldn't remember where the functionality came from : /

I'll check out vim-snippets.  thanks!

**Comment by desmondmonster** [comment]
UPDATE:  the library I was thinking of is https://github.com/tpope/vim-endwise.
