### ISSUE TITLE
Newline after an `=` is not indented

### ISSUE THREAD

**Issue by Mayeu** [elixir-lang/vim-elixir#150]
Hello,

I have met this unexpected behaviour using the plugin, when going into a new line after an `=` the code is not indented.

Current behaviour:
```elixir
changeset =
user
|> build_assoc(:videos)
|> Video.changeset()
```

I would have expected (and I believe it is the general expectation) the code to be indented one level deeper, since everything following the `=`.

Expected behaviour:
```elixir
changeset =
  user
  |> build_assoc(:videos)
  |> Video.changeset
```

I'm using the revision dd8a01aad, so very last one when writing this issue.

Thanks for your nice work on this plugin, and sorry I have no clue how to add this behaviour myself :(

**Comment by kassio** [comment]
I don't know if this is possible to be implemented, because we don't have a 'close' mark. I'm able to implement this if: 
1. All aligned lines starts with the same pattern, for example: `|>`.
2. There is a open mark and a close mark, for example: `[]`, `{}`. 

I'll close this but, please, feel free to reopen if you have an idea about how fix it. 😄

**Comment by Mayeu** [comment]
@kassio Sadly I have no knowledge of all those indentation plugin thingy... What I know is that the [Ruby vim plugin](https://github.com/vim-ruby/vim-ruby) support this kind of indentation without closing mark, so maybe there is some knowledge to gain there? :)

I also realised that newline after a `||` generate the same absence of indentation btw.

**Comment by kassio** [comment]
@Mayeu I'll try to "copy" this feature from `vim-ruby`. Thank you for the reference. 😄

**Comment by kassio** [comment]
Fixed on [master](https://github.com/elixir-lang/vim-elixir/commit/fe61852c744627394c8845925dfba39aa6ac1ca4)
