### ISSUE TITLE
Illegal character <j>: formatoptions+=croqlj found in elixir.vim

### ISSUE THREAD

**Issue by jlem** [elixir-lang/vim-elixir#153]
https://github.com/elixir-lang/vim-elixir/blob/master/ftplugin/elixir.vim#L57

Running vim on OSX (not gvim or macvim), installed with pathogen.

Is there a dependency that I need to update?

**Comment by kassio** [comment]
Your vim is probably outdated. [`j` options is in vim since vim 7.3.541](https://github.com/vim/vim/commit/8134039744ffa581f7c217df58131b709317c1c8)
