### ISSUE TITLE
Illegal character <j>: formatoptions+=croqlj

### ISSUE THREAD

**Issue by toretto460** [elixir-lang/vim-elixir#154]
i've an error, the plugin was installed via `plug`

The error seem at this line https://github.com/elixir-lang/vim-elixir/blob/master/ftplugin/elixir.vim#L57

<img width="703" alt="screen shot 2016-04-30 at 14 21 24" src="https://cloud.githubusercontent.com/assets/1193857/14935815/7f5c0bde-0edf-11e6-8050-e2f47071bc22.png">

**Comment by kassio** [comment]
Your vim is probably outdated. Look #153.
