### ISSUE TITLE
Variables not highlighting

### ISSUE THREAD

**Issue by coryc5** [elixir-lang/vim-elixir#157]
While there is no problem with UnusedVariables highlighting, Variables themselves are not being highlighted:

<img width="615" alt="screen shot 2016-06-04 at 9 07 00 pm" src="https://cloud.githubusercontent.com/assets/14861205/15803556/b4fc422a-2a98-11e6-89cc-d218690a9701.png">
<img width="813" alt="screen shot 2016-06-04 at 9 07 31 pm" src="https://cloud.githubusercontent.com/assets/14861205/15803558/b8cccc4e-2a98-11e6-84aa-a87487aee0f1.png">

**Comment by tprado** [comment]
It seems the problem is the regex that matches variables [elixir.vim#L57](https://github.com/elixir-lang/vim-elixir/blob/master/syntax/elixir.vim#L57):

```vim
syn match elixirVariable '@[a-z]\w*'
```

Which should be instead:

```vim
syn match elixirVariable '[@a-z]\w*'
```

**Comment by tprado** [comment]
Actually, my suggestion (i.e. `'[@a-z]\w*'`) also matches function calls, so never mind.

**Comment by kassio** [comment]
I don't think this is meant to be highlighted. However the highlight group name is not very good, this is meant to highlight modules attributes(`@attribute`) not common variables.
