### ISSUE TITLE
Illegal character <j>

### ISSUE THREAD

**Issue by allyraza** [elixir-lang/vim-elixir#159]
the plugin throws an error when editing elixir files in vim 7.4

`E539: Illegal character <j>: formatoptions+=croqlj`

it was introduced in the follwoing commit 
https://github.com/elixir-lang/vim-elixir/commit/ccf9ecbe07c43cb65c6b78352b61975084fb055f

**Comment by kiernan** [comment]
I got this too, with a fresh install of vundle + vim-elixir on osx, vim 7.3, vim-elixir commit/version: fe61852

```
Error detected while processing /Users/me/.vim/bundle/vim-elixir/ftplugin/elixir.vim:
line   57:
E539: Illegal character <j>: formatoptions+=croqlj
```

**Comment by allyraza** [comment]
I sent a pull request

**Comment by jdmiranda** [comment]
I got the same on mac

**Comment by dighjd12** [comment]
getting the same error

**Comment by allyraza** [comment]
to get rid of this for time being until this gets merged edit the vim-elixir plugin under ./vim/ftplugin/ look for 

`setlocal formatoptions-=t formatoptions+=croqlj`
replace it with the follow
`+silent! setlocal formatoptions-=t formatoptions+=croqlj`

**Comment by jdmiranda** [comment]
I just deleted the j and it worked for me.

**Comment by allyraza** [comment]
👍

**Comment by noam87** [comment]
same problem

**Comment by adamhotep** [comment]
For anybody still looking for this, the issue is that `formatoptions` setting `j` was [added in vim 7.3.541](https://github.com/vim/vim/commit/8134039744ffa581f7c217df58131b709317c1c8), so you just need a conditional like this:
```vim
set formatoptions+=croql
if version >= 703
  set formatoptions+=j
endif
```
