### ISSUE TITLE
Doc comments are not being highlighted as comments

### ISSUE THREAD

**Issue by uri** [elixir-lang/vim-elixir#162]
```elixir
@doc """
Correct doc comment highlighting
"""

@docc """
This is how the current highlighting will show a doc comment
"""
```

**Comment by diegonogueira** [comment]
I think single quote should be too.. 

@doc "Correct doc comment highlighting"
@moduledoc "Correct doc comment highlighting"

?

**Comment by uri** [comment]
Yeah that's correct too @diegonogueira 

```elixir
@doc "Correct doc comment highlighting"
@moduledoc "Correct doc comment highlighting"
```

**Comment by uri** [comment]
Current syntax also highlihgts single-triple quotes which is not supported anymore (originally brought up by @dm1try)

https://github.com/elixir-lang/vim-elixir/blob/master/syntax/elixir.vim#L82

https://github.com/elixir-lang/elixir/issues/5049

**Comment by dm1try** [comment]
as I suggested on the Slack channel, if you don't care about interpolations/sigils in doc comments you can try this snippet:
```viml
" ~/.config/nvim/after/syntax/elixir.vim
syn match elixirShortDoc '@\w*doc ".*"'
syn region elixirFullDoc start='@\w*doc """' end='"""'
hi link elixirShortDoc Comment
hi link elixirFullDoc Comment
```

**Comment by kassio** [comment]
@uri, @diegonogueira, @dm1try: is the #163 what you need?

**Comment by diegonogueira** [comment]
Thanks @kassio.

I think the @dm1try after syntax is more complete, works with whole @doc block. 
Maybe @docmodule could be Comment too.. 
What do you think?

```
@doc """
"""
```

```
@doc " doc.. "
```

**Comment by kassio** [comment]
I'll need more time to investigate that, but when I add @dm1try code some indentation breaks. 😢

**Comment by uri** [comment]
@kassio thanks for taking a look, @diegonogueira is correct however, as #163 won't match the official elixir syntax where the `@doc` `@moduledoc` are also in grey.

>I'll need more time to investigate that, but when I add @dm1try code some indentation breaks. 

Could you post the bit of code you tried where the indentation broke?

**Comment by elasticdog** [comment]
Just wanted to bring up `@typedoc` as well, for consistency across the board.

**Comment by kassio** [comment]
After the last commit it'll look like this:

<img width="447" alt="nvim" src="https://cloud.githubusercontent.com/assets/120483/17699831/ef2dc3e6-63ba-11e6-810c-0be3f3e12cbb.png">
