### ISSUE TITLE
"Rule" for function argument parentheses

### ISSUE THREAD

**Issue by sotojuan** [elixir-lang/vim-elixir#167]
I'm trying to replicate my Atom colorscheme in elixir and one of the things I have left is that `atom-elixir` colors function parentheses:

<img width="359" alt="screen shot 2016-08-24 at 3 37 50 pm" src="https://cloud.githubusercontent.com/assets/8217766/17945174/c2e528ae-6a10-11e6-88a0-8b87f801f480.png">

As you can see this is both in function declarations and when a function is called. I've sorta gotten the second one to work but not the first. Is there an easy regex or match I can just paste on my local version of  `vim-elixir` so I can color them in my color scheme config?

Thanks!

**Comment by sotojuan** [comment]
Also if you know how to match variables inside interpolation (`#{match_me}`) that'd be awesome too!

**Comment by kassio** [comment]
Please take a look at `:help pattern` and `:help sym-match`, it can help you with your doubt.
