### ISSUE TITLE
Pipeline indentation breaks while typing.

### ISSUE THREAD

**Issue by offthecuff** [elixir-lang/vim-elixir#173]
This issue presents itself while typing, but doing something like `gg=G` works fine.
Given the following example:

```elixir
defmodule Cool.Mod do
  def atest do
    variable
    |> pipeline
    |> chain
  end 
end
```
From normal mode, with the cursor on a line with a pipeline operator, the following actions will put the cursor at indentation 0.

- `I` `enter`
- `o`

I thought maybe the line would self correct after typing out another pipeline and entering normal mode but it does not.

Additionally, this bug is easy to replicate in a fresh vim instance. While fooling around with it I was able to put it in a state where the indentation was working again.

I tried a bunch of stuff to try to fix this, but so far everything I've done has broken one test case or another.

**Comment by emilsoman** [comment]
The issue is closed, does that mean it's working as you expect @offthecuff ?

**Comment by offthecuff** [comment]
@emilsoman Yea, this fixed the issue I was describing here.
