### ISSUE TITLE
It takes some time to format (indent) a large file

### ISSUE THREAD

**Issue by acrolink** [elixir-lang/vim-elixir#174]
First, thanks for this valuable tool. I have noticed that formatting a big (1 thousand lines of code) `,ex` file with this tool takes significantly longer time than formatting a `PHP` code using VIM's built in PHP formatter. My question, is this normal or do you think improvements can be made to make the formatting process faster? Thank you.

**Comment by kassio** [comment]
I did some improvements on the indentation code, can you try again? Also, can you show me a benchmark, maybe I can use this as a local test to try to improve things. 😄

**Comment by acrolink** [comment]
@kassio , thank you very much.. I will happily test the modified code and provide feedback.
