### ISSUE TITLE
Quotes in heredoc

### ISSUE THREAD

**Issue by mschae** [elixir-lang/vim-elixir#175]
Quotes in heredocs are highlighted as if they'd terminate the string. This leads to incorrect formatting:
![screen shot 2016-09-07 at 13 26 41](https://cloud.githubusercontent.com/assets/473241/18310492/f768745c-74fe-11e6-9387-a21280ef1dbd.png)

It's worse when there is interpolation within the string:
![screen shot 2016-09-07 at 13 29 05](https://cloud.githubusercontent.com/assets/473241/18310509/12220ae2-74ff-11e6-9ee9-a367f932d41a.png)

**Comment by kassio** [comment]
Hi there, I added some pending tests about this problem, and I'll fix it as soon as I can. 😄

**Comment by kassio** [comment]
This is how it'll work now: 
<img width="168" alt="python" src="https://cloud.githubusercontent.com/assets/120483/18380664/4ed038b6-7670-11e6-8615-a4bf60964681.png">

**Comment by mschae** [comment]
Awesome thanks!

Maybe a stupid question but why are moduledocs highlighted differently from normal heredocs.

Either way this helps a lot, thanks a ton!

**Comment by kassio** [comment]
This was a request, you can check it on: #161, #162.

**Comment by mschae** [comment]
That makes sense. Thanks for your great work with this, absolute lifesaver.
