### ISSUE TITLE
Comment highlighting not working properly

### ISSUE THREAD

**Issue by AlexanderChen1989** [elixir-lang/vim-elixir#178]
![image](https://cloud.githubusercontent.com/assets/2957936/18536287/8e2b5438-7b2e-11e6-8a20-64ea3a313d19.png)

**Comment by kassio** [comment]
Can you verify if you're in the last version, this was fixed not long ago. I just tried with master version:
<img width="320" alt="nvim" src="https://cloud.githubusercontent.com/assets/120483/18551528/a8c8a422-7b50-11e6-8396-fbd43098275d.png">
