### ISSUE TITLE
Invalid indentation in pipes

### ISSUE THREAD

**Issue by slashmili** [elixir-lang/vim-elixir#181]
I'm using master branch (0dedd52f16c57b0d37aab7ffb25f3cc95b8be11f)

and when indent my files, it changes to this:
```
defmodule MyMod do
  def export_info(users) do
    {:ok, infos} = users
                   |> Enum.map(fn (u) -> do_something(u) end)
    |> Enum.map(fn (u) ->
      do_even_more(u)
    end)
    |> finall_thing

    infos
  end

  def do_something(u), do: u
  def do_even_more(u), do: u
  def finall_thing(u), do: {:ok, u}
end
```

Looks like we don't cover the case when one of the lines in pipe has multi line body like in `Enum.map`

**Comment by kassio** [comment]
Hi there, I added some pending tests about this problem, and I'll fix it as soon as I can. 😄

**Comment by slashmili** [comment]
Thanks
