### ISSUE TITLE
Escape highlighting in interpolated regex

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#184]
Currently `"hello #{place}"` and `~q(hello #{place}` will properly escape highlighting however `~r/hello #{place}/` will not. I would expect that the escaping would follow the same rules as the previous examples

**Comment by kassio** [comment]
Hi there, I added some pending tests about this problem, and I'll fix it as soon as I can. 😄

**Comment by jbodah** [comment]
Thanks! 😸

**Comment by jbodah** [comment]
Fixed in #213
