### ISSUE TITLE
Odd indent when defining function with guard

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#187]
Typing the following will cause indent level on the blank line to move 5 spaces when I would expect 4

```ex
defmodule Hello do
  defp say_hello(world) when is_binary(world) do


```

**Comment by kassio** [comment]
I added a test for this case but didn't find any problem. Can you try again with the last version? Also, if the problem remains, can you give me a full example?

5e640463d3c96fe9787e06f3866dfbe782331fe6

**Comment by jbodah** [comment]
Just spun up a VM and tested this with a minimal config and it looks like it's some interaction on my side. Updated my plugins and all looks good now, sorry!
