### ISSUE TITLE
more indenting issues

### ISSUE THREAD

**Issue by erez-rabih** [elixir-lang/vim-elixir#188]
continuing #186:
Second case is not indented at all:
```elixir
    case Connection.open(rabbitmq) do
      {:ok, conn} ->
        Woody.info "CONNECTION_SUCCESSFUL"
        {:ok, chan} = Channel.open(conn)
      {:error, error} -> 
      Woody.info "CONNECTION_FAILED"
      :timer.sleep(10000)
    end
```
Second line should not be indented at all:
```elixir
    Enum.each(s.routing_keys, fn k -> Queue.bind(chan, s.queue, s.exchange, routing_key: k) end)
              Basic.consume(chan, s.queue, nil, no_ack: true)
```

**Comment by erez-rabih** [comment]
I pulled master after the latest changes of course

**Comment by erez-rabih** [comment]
Sorry for throwing all those bug at you I'm just not familiar enough with vim-scripts to make the appropriate PRs

**Comment by kassio** [comment]
Can you try to add a pending test? There're some examples in the test suit. Thks. :)

**Comment by kassio** [comment]
Hi @erez-rabih, I like you open the issues, keep doing this. 😄 

I added tests for these cases, however, the `case` one I wasn't able to replicate. The test passed.
I'll work on the other one as soon as I can.

**Comment by kassio** [comment]
I found the problem with the `case`, it happens only while typing. 😢

**Comment by kassio** [comment]
The `case` situation is fixed. 😄
