### ISSUE TITLE
All variables that begins with `_` should be grayed out

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/vim-elixir#196]
Currently this isn't always case.

![image](https://cloud.githubusercontent.com/assets/291639/19646305/1aae224e-99f9-11e6-9ad8-1ddc608f75a0.png)

vs

![image](https://cloud.githubusercontent.com/assets/291639/19646312/242cfa02-99f9-11e6-99d2-bebb58e8dd12.png)

**Comment by jbodah** [comment]
This seems to be due to the character class match `[^)]` not working over multiple lines. Add `\_` before that will match over new lines but I had trouble getting it to work in all cases. Added specs here https://github.com/elixir-lang/vim-elixir/pull/199

**Comment by jbodah** [comment]
Fixed by #215
