### ISSUE TITLE
Add support for vim-surround for EEx

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/vim-elixir#197]
It would be something like:

```vim
if !exists('b:surround_45')
  let b:surround_45 = "<% \r %>"
endif
if !exists('b:surround_61')
  let b:surround_61 = "<%= \r %>"
endif
if !exists('b:surround_35')
  let b:surround_35 = "<%# \r %>"
endif
if !exists('b:surround_5')
  let b:surround_5 = "<% \r %>\n<% end %>"
endif
```

Extracted from https://github.com/avdgaag/vim-phoenix

**Comment by kassio** [comment]
can you open a pull request, please? I think we can add this in `/plugins/vim-surround.vim`, wdyt?

**Comment by arcseldon** [comment]
@hauleth - please can you explain briefly how that is supposed to work?  ie. key bindings and what to do. I raised an issue [here](https://github.com/elixir-editors/vim-elixir/issues/393).  Found the comments in source code, but they were a little too sparse for me to fully understand if issue is local, and I am applying correct keybindings or not.
