### ISSUE TITLE
Heredoc starting with string interpolation should not be recognise as comment

### ISSUE THREAD

**Issue by brianvanburken** [elixir-lang/vim-elixir#211]
If you start a line in a heredoc with string interpolation it recognises it as a comment and starts adding `#` to the next line.

So given this code:

``` elixir
"""
#{number} bottles of beer on the wall, #{number} bottles of beer.
"""
```

After pressing enter at the end of the line it results in a `#` added on the next line:

``` elixir
"""
#{number} bottles of beer on the wall, #{number} bottles of beer.
#
"""
```

Expected behaviour:

``` elixir
"""
#{number} bottles of beer on the wall, #{number} bottles of beer.

"""
```

I'm using vim version 8.0.46 and the latest of master of vim-elixir (d3d964a8b1953e12cdadb77b3f255923f4873637)

**Comment by jbodah** [comment]
I noticed vim-ruby also has this behavior. @brianvanburken do you know of any other languages that handle this situation in the expected way by any chance?

**Comment by brianvanburken** [comment]
Sadly, no. The only language I found that also uses the same character for comments as well for string interpolation is coffee-script. The plugin https://github.com/kchmck/vim-coffee-script has the same problem as I've described

**Comment by kassio** [comment]
This is actually a feature on vim. You can disable this on your vimrc with `set formatopts-=o`. From the documentation:
>o	Automatically insert the current comment leader after hitting 'o' or
	'O' in Normal mode.
