### ISSUE TITLE
`import [defrecord: ...]` does not highlight properly

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#216]
In the following `defrecord` is highlighted as a keyword instead of as an atom

```ex
defmodule XmlElement do
  require Record
  import Record, only: [defrecord: 2, extract: 2]
end
```

**Comment by kassio** [comment]
Can you add screenshots please? And/or a failing test?

**Comment by jbodah** [comment]
<img width="718" alt="test_ex______repos_vim-elixir__-_vimrunner0_04275292178254475" src="https://cloud.githubusercontent.com/assets/6093002/19890000/8aabc4f0-a00e-11e6-904e-ac1fba580ec8.png">
