### ISSUE TITLE
`with` indenting is wrong

### ISSUE THREAD

**Issue by drewolson** [elixir-lang/vim-elixir#224]
Expected:

```elixir
with {:ok, a} <- foo(1),
     {:ok, b} <- foo(2) do
  a + b
end
```

Actual:

```elixir
with {:ok, a} <- foo(1),
{:ok, b} <- foo(2) do
  a + b
end
```

**Comment by kassio** [comment]
Thank you for the report. There are already some pending tests for these cases, I'll fix it as soon as possible.

**Comment by wadeanthony0100** [comment]
Is there active work being done on this? Ive noticed similar issues with other blocks where a multiline declaration that ends with `do` will align the `end` to the wrong level. For example, 

Expected:

```elixir
def f1(%{
  "height" => height,
  "width" => width,
  "data" => data}) do
    Function.Implement
end

def f2(_) do
  Function.Implement
end
```

Actual:

```elixir
def f1(%{
  "height" => height,
  "width" => width,
  "data" => data}) do
Function.Implement
  end

  def f2(_) do
    Function.Implement
  end
```

Thanks!

**Comment by jbodah** [comment]
@wadeanthony0100 `with` support has been pushed off for a bit due to complexity although I might try and pick it back up soon

I just opened up a separate issue [here](https://github.com/elixir-lang/vim-elixir/issues/328) for the other you linked. I should be able to get to it by EOD I think

**Comment by wadeanthony0100** [comment]
Oh wow, awesome thanks!

**Comment by kaelumania** [comment]
@jbodah is there any progress?

**Comment by jbodah** [comment]
@karlumania I assume you're referring to the `with` indent. I spent a little time with it but tabled it. I have an idea I can try for matching `with`/`do` today sometime

For the record for future parties - please keep this issue about `with` indent

**Comment by kaelumania** [comment]
@jbodah yes I mean the `with` issue. for example, I use very often something like

```elixir
with {:ok, a} <- foo(1),
     {:ok, b} <- foo(2)
do
  a + b
end
```

**Comment by jbodah** [comment]
@kaelumania I still need to add support for pattern matching in the `else/end` but you can use the dev branch for this if you'd like: https://github.com/elixir-lang/vim-elixir/pull/336
