### ISSUE TITLE
Broken highlithing

### ISSUE THREAD

**Issue by dm1try** [elixir-lang/vim-elixir#230]
in many different places of Elixir stdlib or in deps like `ecto` the highlithing is broken
This was checked in `neovim` and `vim`(with only installed `vim-elixir`) 
![h](https://cloud.githubusercontent.com/assets/486807/20544175/c91768fe-b119-11e6-8969-ade6fca5e947.png)

![hi](https://cloud.githubusercontent.com/assets/486807/20543988/0165e182-b119-11e6-9e83-3844849db131.png)

**Comment by kassio** [comment]
@lmarlow can you help me with this one?

**Comment by tsubery** [comment]
Coincidentally I encountered this issue yesterday and did some investigation. As far as I can tell the regex used by vim-elixir to end doctest region is inaccurate. The regex looks for a empty line or line that only has spaces while the a valid doctest can end with the end of the whole documentation marker of: """.
I can make sure my assumptions are correct and open a pull request if you want.

**Comment by dm1try** [comment]
@kassio , @lmarlow thanks guys! It looks great now :sparkles:
