### ISSUE TITLE
indentation not working

### ISSUE THREAD

**Issue by blset** [elixir-lang/vim-elixir#238]
hello,

nothing changes in an elixir file when I ask for indentation using for instance gg=G

also, cannot find the plugin documentation

thanks

**Comment by pbogut** [comment]
I had a similar problem because I was using vim-polyglot. `let g:polyglot_disabled = ['elixir']` fixed the problem.

**Comment by blset** [comment]
thanks it works now, although some code is not indented ok
for instance one liner 
` if test, do: expr, else: expr`
is not indented ok 
it's ok if written
```
if test do
  expr
else
  expr
end
```

**Comment by blset** [comment]
also indentation problem with anonymous functions `fn x -> .... end` on several lines

thanks

**Comment by pbogut** [comment]
Well, there is several indent [issues](https://github.com/elixir-lang/vim-elixir/issues) open right now.

**Comment by kassio** [comment]
I'll close this one since the original problem was solved. I'll try to fix the indentation problems asap, but I'm without time for now, so I'll ask a little patience from you. 😊
