### ISSUE TITLE
Broken highlighting in heredocs in tests

### ISSUE THREAD

**Issue by devonestes** [elixir-lang/vim-elixir#239]
First off, thanks for this project! Makes using Vim & Elixir a lot easier 😄 

I noticed recently that highlighting is broken for heredocs, but only in my tests for some reason. For example, I was working on Credo and I see this in a test file:

![highlighting](https://cloud.githubusercontent.com/assets/8422484/21296076/0481c198-c563-11e6-9193-6c15fff0b7a0.png)

It looks like it's not seeing the closing `"""` of the heredoc for some reason. I've tried assigning the heredoc to a variable so the closing `"""` could be on its own line, but that didn't solve the issue. I also tried changing the file extension to `.ex` from `.exs`, and that didn't do anything, either. I saw #230 and just updated all my plugins (I'm using Vundle), and still no dice.

Let me know if there's any more info or debugging data I can pass along to help fix this or if there's something I'm just totally missing.

**Comment by dm1try** [comment]
btw, the workaround tip - move this heredoc string to the right :)
should be helpful for fixing
![src](https://cloud.githubusercontent.com/assets/486807/21296236/41a79812-c578-11e6-9e8f-c3f5583b0f88.png)

**Comment by devonestes** [comment]
@dm1try Thanks for the quick response!

That workaround will actually change behavior in our tests, since Credo is a linting tool, exact indentation in these strings counts. Those two spaces before `defmodule` and `end` will change behavior in a critical way (not necessarily in this particular test, but in several others). If there were a heredoc that stripped leading whitespace then we'd be in business, but unfortunately that doesn't exist in Elixir (yet?), and it'll be a real hassle to add a bunch of code to strip whitespace just so I can get the proper highlighting happening (and I don't think it would be accepted cause it would just be solving a problem for me).

Any chance we could get this to work without having to indent like that? I'm not really a vimscript master, and I'm even worse with regex, so I'm not sure I'm a great person to tackle this particular issue...
