### ISSUE TITLE
E492: Not an editor command

### ISSUE THREAD

**Issue by naviehuynh** [elixir-lang/vim-elixir#243]
I get these errors on Linux Mint when vim-elixir is enabled (Vundle), probably a line ending issue?

```
Error detected while processing /home/nav/.vim/bundle/vim-elixir/ftdetect/elixir.vim:
line    4:
E492: Not an editor command: ^M
line    6:
E492: Not an editor command: ^M
line    7:
E488: Trailing characters
line   10:
E492: Not an editor command: ^M
line   11:
E488: Trailing characters
```

**Comment by jbodah** [comment]
@naviehuynh have you seen this issue? My local doesn't seem to clean out extra characters so they may be being added by git automagically https://github.com/VundleVim/Vundle.vim/issues/445

**Comment by naviehuynh** [comment]
it works, thanks @jbodah
