### ISSUE TITLE
Indent: state can cause unexpected errors when indenting a single line

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#255]
I don't have an example here, but the indent code is only called sequentially when indenting multiple lines. In particular, opening a new buffer and indenting only a single line can lead to cases where things like `b:old_ind.pipeline` is not set and can lead to unexpected results

**Comment by jbodah** [comment]
On second thought there may be no way around this one

**Comment by kassio** [comment]
Agree with your last comment. :)
