### ISSUE TITLE
indentation break for = symbol

### ISSUE THREAD

**Issue by gasparch** [elixir-lang/vim-elixir#264]
@kassio cb633c0  commit breaks indentation (at least in my environment :)

```elixir
defmodule A do
  def foo() do
    a = test()

    b = test2()
  end
end
```

Selecting whole module and pressing `=` will result in following code, which is wrong. 
Code snippet should stay as it was ;)

```elixir
defmodule A do
  def foo() do
    a = test()

b = test2()
  end
end
```

**Comment by kassio** [comment]
I think this is related to: #262, #208 and #200

**Comment by gasparch** [comment]
Just to make sure - 8897668 works totally okay, it is exactly cb633c05 that breaks the stuff.
