### ISSUE TITLE
Indent: indent inconsistencies when typing/indenting single line

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#272]
Two cases here, but I felt it was important to talk about both together. Really annoying behavior that I don't know the correct approach for -

As I type the indent is incorrect:

<img width="250" alt="1__hello_ex______repos_modern_pastry__-_vim__vim_" src="https://cloud.githubusercontent.com/assets/6093002/22216559/92197502-e16d-11e6-91b3-a4c73d35d2e3.png">

Then indenting the block gets me the correct indent:

<img width="254" alt="1__hello_ex______repos_modern_pastry__-_vim__vim_" src="https://cloud.githubusercontent.com/assets/6093002/22216455/2a4ae5be-e16d-11e6-91f2-4fdec4460d1a.png">

But if we indent a single line we get messed up:

<img width="268" alt="1__hello_ex______repos_modern_pastry__-_vim__vim_" src="https://cloud.githubusercontent.com/assets/6093002/22216489/4d0a1fa2-e16d-11e6-92e9-8632e9630401.png">

**Comment by jbodah** [comment]
Should also note it would be amazing to have a way to unit test all of these cases

**Comment by gasparch** [comment]
randomize offsets in front of any line and try indent that single line?
also randomize offsets on all lines - both left and right shifts and then try to indent whole block?

so each test will run actually *line_num* tests

I think also it can be done with deleting content starting from some line, emulating Enter press and checking if indent level is same as it is in the test.

**Comment by jbodah** [comment]
I was thinking more along the lines of having a few more vimrunner-based matchers that would:

* Type out the input string char-by-char. Assert indentation is correct (Tests it properly indents as you type)

* Paste the input. Line indent each line (e.g. `==`). Assert indentation is correct between each indent. This may be difficult due to dependence on state https://github.com/elixir-lang/vim-elixir/issues/255. I feel like vim-ruby does this well though, so I don't know what the secret sauce is here

**Comment by gasparch** [comment]
something like this ? https://github.com/gasparch/vim-elixir/tree/randomize_tests

**Comment by jbodah** [comment]
> something like this ? https://github.com/gasparch/vim-elixir/tree/randomize_tests

Would the goal of this be to find edge cases? Does running this find any more errors? If this uses `gg=G` then I think this is more-or-less just testing the same code path that the tests are already testing

I was thinking more of just creating new matchers to handle the two cases I mentioned in the initial issue. I think those cases should rely on an approach other than `gg=G`

**Comment by jbodah** [comment]
Looks like `be_typed_with_right_indent` already exists

**Comment by gasparch** [comment]
there is a code to call randomize on each line of supplied block as well '10G=='.

May be 'as you type matcher' should be also run for ordinary tests. So there will be no need to add/modify existing tests.

**Comment by gasparch** [comment]
Oops. I did not pushed commits with per-line indent tests. Please check out now :)

**Comment by jbodah** [comment]
Fixed in 3621b9253aabb629b3a7280b241726444bef2a66
