### ISSUE TITLE
indention of a multiline map

### ISSUE THREAD

**Issue by nhooyr** [elixir-lang/vim-elixir#284]
```elixir
changes = Dict.merge(%{
  name: "Some User",
  username: "user%{Base.encode16(:crypto.rand_bytes(8))}",
  password: "supersecret",
}, attrs)
```

is indented as

```elixir
changes = Dict.merge(%{
                       name: "Some User",
                       username: "user%{Base.encode16(:crypto.rand_bytes(8))}",
                       password: "supersecret",
                     }, attrs)
```

I'm not sure if this is wrong but I find it a lot harder to read because of how wide the lines are now. Could there be an option to configure this?

**Comment by nhooyr** [comment]
The same thing happens with multiline function calls.

**Comment by jbodah** [comment]
This behavior is intended, but I'm open to opinions on how we think this should be. I think ideally this would be configurable

**Comment by jbodah** [comment]
Intentional or not, this is no longer the case on master - closing
