### ISSUE TITLE
string interpolation followed by "when" breaks highlighting

### ISSUE THREAD

**Issue by bismark** [elixir-lang/vim-elixir#290]
Example:

```
"#{foo} when"
```

The highlighting appears to think that the string ends with the closing `}` so the final `"` acts as an opening quote for the rest of the file.

**Comment by mhinz** [comment]
Using the given example with the current master seems to work as expected; `when` is still part of `elixirString`.

I guess this was silently fixed in the meanwhile, so I'm closing this.

Thanks for reporting!
