### ISSUE TITLE
syntax: :queue.in should not be highlighted as a keyword

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#299]
`hi<airline_x_to_airline_y_bold> trans<airline_x_to_airline_y_bold> lo<Statement>`

**Comment by mhinz** [comment]
Sorry, but I'm confused. Has the example anything to do with the `:queue.in/2` mentioned in the title? :->

Anyway, I noticed this:

```elixir
x = :queue.new
x = :queue.in(5, x)
```

In this case, the `new` is highlighted as `elixirId`, whereas the `in` is highlighted as `elixirOperator`. (I guess that's what you meant.)

**Comment by jbodah** [comment]
Yep - the problem is that the leading `.` in `.in` should cause it to be recognized not as an operator, but as an identifier/function name

**Comment by mhinz** [comment]
Woah, this is tricky to get right.

E.g., `<-` is only highlighted as operator, because it matches twice! For `<` and for `-`. This means, just prepending something to the `elixirOperator` regexp to not match after `.` won't work, because in the case of `.<-`, the `<` won't be highlighted, but the `-` still will.

**Comment by jbodah** [comment]
> Has the example anything to do with the :queue.in/2 mentioned in the title?

Sorry I just realized I never responded to this. No, the "example" isn't really an example and is frankly useless (it was the syntax groups but those are obscured by airline). The example you gave is what to use

> E.g., <- is only highlighted as operator, because it matches twice! For < and for -. This means, just prepending something to the elixirOperator regexp to not match after . won't work, because in the case of .<-, the < won't be highlighted, but the - still will.

Yeah - these are pretty fringe, but here's an example from the Kernel module: https://github.com/elixir-lang/elixir/blob/v1.4.5/lib/elixir/lib/kernel.ex#L1013

```ex
  def left ++ right do
    :erlang.++(left, right)
  end
```

Thus,  I think the `++` in the signature should be considered an operator, but the `.++` in the body is a function name. This is really fringe and almost no one calls these operators with a `.` so I'm indifferent on if/when we choose to support these, however the keyword "operators" (`and`, `or`, etc) should definitely be supported in case other modules use them (as is the case in `:queue.in`)

**Comment by mhinz** [comment]
I agree. I'm playing around with different approaches right now, but when everything fails, I'll just change from..

```vim
syn keyword elixirOperator and not or in
```

to

```vim
syn match elixirOperator '\v\.@<!%(and|or|in|not)'
```

Then we at least catch the most common cases.

**Comment by jbodah** [comment]
:+1: that seems good to me
