### ISSUE TITLE
MacVim was frozen when writing `->` in certain scenario. 

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/vim-elixir#317]
```
defmodule Foo do
  def run do
    with a = 1 do
      else - # cannot type `else ->` it will freeze MacVim
    end
  end
end
```

On latest version of MacVim and vim-elixir.

**Comment by jbodah** [comment]
`searchpair` is entering an infinite loop. Not sure why this is even a feature, but adding `W` to searchpair fixes this. Will update soon
