### ISSUE TITLE
Unused variables not highlighted in anonymous functions

### ISSUE THREAD

**Issue by mgartner** [elixir-lang/vim-elixir#333]
In the following code, `_unused` is not getting the same color as comments. This used to work.

```ex
fun = fn _unused -> false end

fun  = fn
  ([], _unused) -> false
  (list, _unused) -> list
end

_unused = false
```

**Comment by jbodah** [comment]
I've noticed this as well. There might be a reason we didn't do this, but I can't remember off the top of my head. Let me poke around a bit
