### ISSUE TITLE
Unexpected highlight in comment

### ISSUE THREAD

**Issue by gmile** [elixir-lang/vim-elixir#347]
# Actual

In the following code snipped `XXX` is being highlighted:

```elixir
defmodule Abc do
  # some comment XXX
end
```

Screenshot:
![image](https://user-images.githubusercontent.com/207112/27995015-64077916-64d0-11e7-91d1-14896f112049.png)

# Expected

`XXX` is not highlighted (just like YYY, ZZZ, etc.):

```elixir
defmodule Abc do
  # some comment XXX
end
```
Screenshot:
![image](https://user-images.githubusercontent.com/207112/27995049-8ab0a1dc-64d0-11e7-9dff-7d036c159729.png)

**Comment by jbodah** [comment]
Hey, thanks for the report. This is being highlighted because it is being parsed as a TODO:

https://github.com/elixir-lang/vim-elixir/blob/master/syntax/elixir.vim#L17

**Comment by gmile** [comment]
@jbodah oh, nice! I didn't know that. Closing this then.
