### ISSUE TITLE
Add details how to check your syntastic version to syntastic warning in the README.md

### ISSUE THREAD

**Issue by cpdean** [elixir-lang/vim-elixir#348]
It's great that the unsafe syntax-checking implementation of syntastic for elixir files is called out in the [readme](https://github.com/elixir-lang/vim-elixir#syntastic-integration), but should something be included to explain how to check your version of syntastic?

One way is to echo the global that syntastic uses to identify the version:

```
:echo g:_SYNTASTIC_VERSION
```

**Comment by jbodah** [comment]
Nice suggestion - added 434d1d07a5a2bcd8163a47e36b6d52acc9983630

**Comment by cpdean** [comment]
awesome, thanks!
