### ISSUE TITLE
Could I join the fine vim-elixir team?

### ISSUE THREAD

**Issue by mhinz** [elixir-lang/vim-elixir#356]
Hi,

I'd like to join the vim-elixir team.

I intend to mainly work at:

- Squashing all of the coarser syntax and indent bugs.
- Adding Neovim support for the testing suite.
- Improving the indent speed in large files. This is probably the hardest part, due to all the regular expressions that look back.

I'm a long-time Vim nut and know some bits about it. And I learned to love Elixir recently. What a great combination!

CC @jbodah @josevalim

**Comment by jbodah** [comment]
I'd love more help - I don't have admin for this repo though. @josevalim would you be able to add @mhinz?

**Comment by josevalim** [comment]
Welcome @mhinz!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mhinz** [comment]
Thank you! 🎉
