### ISSUE TITLE
errorformat doesn't parse errors very well

### ISSUE THREAD

**Issue by jarednorman** [elixir-lang/vim-elixir#76]
Using vim-dispatch and all the quickfix window ends up displaying is the name of the test which isn't exactly what I'd hope.

![screenshot](http://cl.ly/image/3F233Y2K3V1f/Screen%20Shot%202014-06-03%20at%207.07.29%20PM.png)

**Comment by copenhas** [comment]
I have been working on this and I think I have a solution (wow are error format strings a pain in the ass). I wanted to do more testing before submitting a PR, but if someone else wants to play around here's the commit:

https://github.com/copenhas/vim-elixir/commit/5efd96ced7260fb4dd241828222405e1b1d3beb3

**Comment by carlosgaldino** [comment]
Can someone here try #118 and see if it fixes the problem? Thanks.

**Comment by kassio** [comment]
Since it has two months, I'll consider that #118 fixed this problem. If the problem persists, please feel free to reopen the issue.

**Comment by patrickdavey** [comment]
@kassio I'm having a small amount of trouble using `dispatch.vim` with `elixir`, and I'm unsure if it's down to `errorformat`, but I think it might be.

Anyway, I use vim-dispatch with [janko-m/vim-test](https://github.com/janko-m/vim-test) and when I run the tests in vim-dispatch, if they all pass (and they do) then it should just run in the background and not-interrupt. However, with Elixir the tests do run, but vim-dispatch still pops open.

I don't suppose you use [vim-dispatch](https://github.com/tpope/vim-dispatch) and happen to see the same issues. I'm happy to have a crack at fixing things, but I'm just not quite sure where the problem should be fixed (here, or vim-dispatch, or vim-test), any pointers to where to start would be great!

**Comment by patrickdavey** [comment]
I've created an repo which outlines the issue I'm having. https://github.com/patrickdavey/sample I've also opened an [issue on vim-test](https://github.com/janko-m/vim-test/issues/149) in case the issue is there.

**Comment by patrickdavey** [comment]
Aaaand just in case anyone else comes across this, the solution is to add

`let g:dispatch_compilers = {'elixir': 'exunit'}` 

inside your `.vimrc` to tell vim-dispatch which compiler to use.

Many thanks to [janko-m on his vim-test comment](https://github.com/janko-m/vim-test/issues/149#issuecomment-257103619) which explained and solved everything.

**Comment by alexcastano** [comment]
Hello,

I'm not sure if it is my local configuration, or I'm expecting a behavior that it isn't the current one, or it is just `errorformat` for `exunit` is not working correctly.

When I run vim-test with vim-dispatch in a Elixir project, the quickfix list is filled like this:

![image](https://user-images.githubusercontent.com/1745859/57579370-26ba3080-749b-11e9-9f70-ee551fa84607.png)

It is the real output of the `mix test` command, but it doesn't parse correctly the file and the line number, so I'm not able to jump among the errors. In fact, in this example where there are two errors, but the quicklist is filled with 4 errors.
