### ISSUE TITLE
Folding doesn't work

### ISSUE THREAD

**Issue by danieljaouen** [elixir-lang/vim-elixir#88]
I have a module with two functions.  I should be able to fold either the whole module, or each function individually.  Instead, the module folds "over" the first function only.  See the screen shots below for clarification.

Unfolded:
![elixir-unfolded](https://cloud.githubusercontent.com/assets/766444/4432083/c73bab82-4684-11e4-82a9-7298f4b58c07.png)

Folded:
![elixir-folded](https://cloud.githubusercontent.com/assets/766444/4432084/da0efea8-4684-11e4-9057-82c2dcaeb958.png)

**Comment by schnittchen** [comment]
I can confirm this (using latest version as of now).

**Comment by wajsel** [comment]
perhaps not viewed as a correct solution but while this is getting corrected I'm happy with the following
`set foldmethod=indent`
this requires you put the "end" to match the beginning so you can fold modules and functions.
this does not fold docstrings separately from functions.

**Comment by schnittchen** [comment]
As a lame workaround, switching to ruby syntax works surprisingly well.

**Comment by schnittchen** [comment]
Thanks @kassio, works fine!
